package com.assurance.enums;

public enum NatureMouvementTresorerie {
    REGLEMENT_CLIENT,
    REGLEMENT_COMPAGNIE,
    ANNULATION_REGLEMENT_COMPAGNIE,
    REJET_INSTRUMENT,
    REMISE_BANQUE,
    SINISTRE,
    ANNULATION_SINISTRE,
    TRANSFERT,
    AJUSTEMENT
}
